<?php $submission=$contentData['submission']??null; $values=(array)($contentData['values']??[]); ?>
<section class="eco-card"><h1>Landing Submission Detail</h1><p><strong>Aviso:</strong> modo read-only. No se expone raw_data_json/value_json, file_path ni s3_key.</p>
<?php if(is_array($submission)): ?><p><a href="/crm/submission-to-lead/<?= (int)$submission['id'] ?>/dry-run">Simular conversión a lead (dry-run)</a></p><?php endif; ?>
<?php if(!is_array($submission)): ?><p>Submission no encontrada.</p><?php else: ?>
<ul><li>ID: <?= (int)$submission['id'] ?></li><li>Form: <?= htmlspecialchars((string)$submission['form_name']) ?></li><li>Landing page: <?= htmlspecialchars((string)$submission['landing_page_title']) ?></li><li>Contact: <?= htmlspecialchars((string)($submission['contact_name_preview']??'-')) ?></li><li>Email: <?= htmlspecialchars((string)($submission['email_preview']??'-')) ?></li><li>Phone: <?= htmlspecialchars((string)($submission['phone_preview']??'-')) ?></li><li>IP preview: <?= htmlspecialchars((string)($submission['ip_address_preview']??'-')) ?> (exposed=false)</li><li>User agent preview: <?= htmlspecialchars((string)($submission['user_agent_preview']??'-')) ?></li><li>coords present: <?= !empty($submission['coordinates_present'])?'true':'false' ?> (exposed=false)</li></ul>
<table class="eco-table"><thead><tr><th>ID</th><th>Field</th><th>value_text</th><th>value_json</th><th>file_path</th><th>s3_key</th><th>created_at</th></tr></thead><tbody>
<?php foreach($values as $v): ?><tr><td><?= (int)$v['id'] ?></td><td><?= htmlspecialchars((string)$v['field_label']) ?> (<?= htmlspecialchars((string)($v['field_key_preview'] ?? '-')) ?>, exposed=false)</td><td><?= !empty($v['value_text_present'])?htmlspecialchars((string)($v['value_text_preview']??'present')):'-' ?> (exposed=false)</td><td><?= !empty($v['value_json_present'])?'present (hidden)':'-' ?></td><td><?= !empty($v['file_path_present'])?'present (hidden)':'-' ?></td><td><?= !empty($v['s3_key_present'])?'present (hidden)':'-' ?></td><td><?= htmlspecialchars((string)($v['created_at']??'')) ?></td></tr><?php endforeach; ?>
</tbody></table>
<?php endif; ?></section>
