<?php
declare(strict_types=1);
namespace App\Core\Cloud;
use PDO;
final readonly class CloudFileRepository{public function __construct(private PDO $pdo){}
public function listByUser(int $tenantId,int $userId,int $limit=100): array{$stmt=$this->pdo->prepare('SELECT id, original_name, extension, mime_type, size_bytes, status, virus_scan_status, access_type, found_in_s3, uploaded_at FROM cloud_files WHERE tenant_id = :tenant_id AND user_id = :user_id AND status <> :status_deleted ORDER BY uploaded_at DESC, id DESC LIMIT :limit');$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':user_id',$userId,PDO::PARAM_INT);$stmt->bindValue(':status_deleted','deleted');$stmt->bindValue(':limit',$limit,PDO::PARAM_INT);$stmt->execute();return $stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}
public function findByIdForUser(int $tenantId,int $userId,int $id): ?array{$stmt=$this->pdo->prepare('SELECT id, original_name, stored_name, s3_key, mime_type, extension, size_bytes, checksum_sha256, etag, storage_class, origin_module, origin_table, origin_id, access_type, secure_hint, encrypted, encryption_key_ref, found_in_s3, virus_scan_status, status, uploaded_at, updated_at FROM cloud_files WHERE id = :id AND tenant_id = :tenant_id AND user_id = :user_id LIMIT 1');$stmt->execute([':id'=>$id,':tenant_id'=>$tenantId,':user_id'=>$userId]);$row=$stmt->fetch(PDO::FETCH_ASSOC);return is_array($row)?$row:null;}
public function archiveByIdForUser(int $tenantId,int $userId,int $id): bool{$stmt=$this->pdo->prepare('UPDATE cloud_files SET status = :status, updated_at = NOW() WHERE id = :id AND tenant_id = :tenant_id AND user_id = :user_id');return $stmt->execute([':status'=>'archived',':id'=>$id,':tenant_id'=>$tenantId,':user_id'=>$userId])&&$stmt->rowCount()>0;}
public function trashByIdForUser(int $tenantId,int $userId,int $id): bool{$stmt=$this->pdo->prepare('UPDATE cloud_files SET status = :status, deleted_at = NOW(), updated_at = NOW() WHERE id = :id AND tenant_id = :tenant_id AND user_id = :user_id');return $stmt->execute([':status'=>'deleted',':id'=>$id,':tenant_id'=>$tenantId,':user_id'=>$userId])&&$stmt->rowCount()>0;}}
