<?php
declare(strict_types=1);
namespace App\Core\BrowserAnalytics;
final readonly class EcosistemaBrowserAnalyticsPageviewService{public function __construct(private EcosistemaBrowserAnalyticsPageviewRepository $repository,private EcosistemaBrowserAnalyticsAdapter $adapter){}
public function listRecent(int $tenantId,int $limit=100): array{return ['summary'=>$this->normalizeSummary($this->repository->summarizePageviews($tenantId)),'items'=>$this->normalizeRows($this->repository->listRecentPageviews($tenantId,$limit)),'mode'=>'read-only','db_write'=>false,'capabilities'=>$this->adapter->capabilities()];}
public function listForSession(int $tenantId,int $sessionId,int $limit=100): array{return ['summary'=>$this->normalizeSummary($this->repository->summarizePageviews($tenantId)),'items'=>$this->normalizeRows($this->repository->listPageviewsForSession($tenantId,$sessionId,$limit)),'session_id'=>$sessionId,'mode'=>'read-only','db_write'=>false,'capabilities'=>$this->adapter->capabilities()];}
private function normalizeSummary(array $summary): array{return ['total_pageviews'=>(int)($summary['total_pageviews']??0),'total_sessions'=>(int)($summary['total_sessions']??0),'latest_viewed_at'=>$summary['latest_viewed_at']??null,'avg_duration_ms'=>(float)($summary['avg_duration_ms']??0),'avg_scroll_depth_percent'=>(float)($summary['avg_scroll_depth_percent']??0)];}
private function normalizeRows(array $rows): array{return array_map(fn(array $row): array=>$this->toReadOnlyDto($row),$rows);}
private function toReadOnlyDto(array $row): array{$pageUrl=(string)($row['page_url']??'');$referrer=(string)($row['referrer_url']??'');return ['id'=>(int)($row['id']??0),'session_id'=>(int)($row['session_id']??0),'campaign_id'=>isset($row['campaign_id'])?(int)$row['campaign_id']:null,'landing_page_id'=>isset($row['landing_page_id'])?(int)$row['landing_page_id']:null,'short_link_id'=>isset($row['short_link_id'])?(int)$row['short_link_id']:null,'crm_lead_id'=>isset($row['crm_lead_id'])?(int)$row['crm_lead_id']:null,'page_url_present'=>$pageUrl!=='','page_url_preview'=>$this->sanitizeUrlPreview($pageUrl),'page_url_exposed'=>false,'page_title'=>(string)($row['page_title']??''),'referrer_url_present'=>$referrer!=='','referrer_url_preview'=>$this->sanitizeUrlPreview($referrer),'path'=>(string)($row['path']??''),'query_string_present'=>((string)($row['query_string']??''))!=='','query_string_exposed'=>false,'hash_fragment_present'=>((string)($row['hash_fragment']??''))!=='','hash_fragment_exposed'=>false,'viewed_at'=>$row['viewed_at']??null,'duration_ms'=>isset($row['duration_ms'])?(int)$row['duration_ms']:null,'scroll_depth_percent'=>isset($row['scroll_depth_percent'])?(float)$row['scroll_depth_percent']:null,'is_landing_view'=>((int)($row['is_landing_view']??0))===1,'is_campaign_view'=>((int)($row['is_campaign_view']??0))===1,'meta_json_present'=>((string)($row['meta_json']??''))!=='','meta_json_exposed'=>false,'mode'=>'read-only','db_write'=>false];}
private function sanitizeUrlPreview(string $url): string{if($url===''){return '';} $parts=parse_url($url); if(!is_array($parts)){return substr($url,0,80);} $scheme=isset($parts['scheme'])?$parts['scheme'].'://':'';$host=$parts['host']??'';$path=$parts['path']??''; $preview=$scheme.$host.$path; return substr($preview,0,140);}}
