<?php
declare(strict_types=1);
namespace App\Core\BrowserAnalytics;
use PDO;
final readonly class EcosistemaBrowserAnalyticsDashboardRepository{public function __construct(private PDO $pdo){}
public function summarizeTenant(int $tenantId): array{$sql='SELECT COALESCE(SUM(sessions_count),0) AS total_sessions,COALESCE(SUM(pageviews_count),0) AS total_pageviews,COALESCE(SUM(events_count),0) AS total_events,COALESCE(SUM(conversions_count),0) AS total_conversions,COALESCE(AVG(avg_duration_ms),0) AS avg_duration_ms,COALESCE(AVG(avg_scroll_depth_percent),0) AS avg_scroll_depth_percent FROM browser_analytics_daily_rollups WHERE tenant_id=:tenant_id';$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->execute();return (array)($stmt->fetch(PDO::FETCH_ASSOC)?:[]);} 
public function summarizeDailyRollups(int $tenantId,int $days=30): array{$safeDays=max(1,min(365,$days));$sql='SELECT rollup_date,COALESCE(sessions_count,0) AS sessions_count,COALESCE(pageviews_count,0) AS pageviews_count,COALESCE(events_count,0) AS events_count,COALESCE(conversions_count,0) AS conversions_count FROM browser_analytics_daily_rollups WHERE tenant_id=:tenant_id AND rollup_date>=DATE_SUB(CURDATE(), INTERVAL :days DAY) ORDER BY rollup_date DESC LIMIT 400';$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':days',$safeDays,PDO::PARAM_INT);$stmt->execute();return $stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}
public function summarizeByCampaign(int $tenantId,int $limit=50): array{$safeLimit=max(1,min(200,$limit));$sql='SELECT COALESCE(c.name, CONCAT("Campaign #", dr.campaign_id)) AS campaign_label,COALESCE(SUM(dr.sessions_count),0) AS sessions_count,COALESCE(SUM(dr.pageviews_count),0) AS pageviews_count,COALESCE(SUM(dr.events_count),0) AS events_count,COALESCE(SUM(dr.conversions_count),0) AS conversions_count FROM browser_analytics_daily_rollups dr LEFT JOIN crm_marketing_campaigns c ON c.id=dr.campaign_id WHERE dr.tenant_id=:tenant_id AND dr.campaign_id IS NOT NULL GROUP BY dr.campaign_id,c.name ORDER BY sessions_count DESC,campaign_label ASC LIMIT :limit';$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':limit',$safeLimit,PDO::PARAM_INT);$stmt->execute();return $stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}
public function summarizeByLandingPage(int $tenantId,int $limit=50): array{$safeLimit=max(1,min(200,$limit));$sql='SELECT COALESCE(lp.title, CONCAT("Landing #", dr.landing_page_id)) AS landing_label,COALESCE(SUM(dr.sessions_count),0) AS sessions_count,COALESCE(SUM(dr.pageviews_count),0) AS pageviews_count,COALESCE(SUM(dr.events_count),0) AS events_count,COALESCE(SUM(dr.conversions_count),0) AS conversions_count FROM browser_analytics_daily_rollups dr LEFT JOIN landing_pages lp ON lp.id=dr.landing_page_id AND lp.tenant_id=dr.tenant_id WHERE dr.tenant_id=:tenant_id AND dr.landing_page_id IS NOT NULL GROUP BY dr.landing_page_id,lp.title ORDER BY sessions_count DESC,landing_label ASC LIMIT :limit';$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':limit',$safeLimit,PDO::PARAM_INT);$stmt->execute();return $stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}}
