<?php
declare(strict_types=1);
namespace App\Core\BrowserAnalytics;
final readonly class EcosistemaBrowserAnalyticsEventService{public function __construct(private EcosistemaBrowserAnalyticsEventRepository $repository,private EcosistemaBrowserAnalyticsAdapter $adapter){}
public function listRecent(int $tenantId,int $limit=100): array{return ['summary'=>$this->normalizeSummary($this->repository->summarizeEvents($tenantId)),'items'=>$this->normalizeRows($this->repository->listRecentEvents($tenantId,$limit)),'mode'=>'read-only','db_write'=>false,'capabilities'=>$this->adapter->capabilities()];}
public function listForPageview(int $tenantId,int $pageviewId,int $limit=100): array{return ['summary'=>$this->normalizeSummary($this->repository->summarizeEvents($tenantId)),'items'=>$this->normalizeRows($this->repository->listEventsForPageview($tenantId,$pageviewId,$limit)),'pageview_id'=>$pageviewId,'mode'=>'read-only','db_write'=>false,'capabilities'=>$this->adapter->capabilities()];}
private function normalizeSummary(array $summary): array{return ['total_events'=>(int)($summary['total_events']??0),'total_pageviews'=>(int)($summary['total_pageviews']??0),'total_sessions'=>(int)($summary['total_sessions']??0),'latest_occurred_at'=>$summary['latest_occurred_at']??null,'avg_score_points'=>(float)($summary['avg_score_points']??0)];}
private function normalizeRows(array $rows): array{return array_map(fn(array $row): array=>$this->toReadOnlyDto($row),$rows);}private function toReadOnlyDto(array $row): array{$elementUrl=(string)($row['element_url']??'');$valueText=(string)($row['value_text']??'');$metadata=(string)($row['metadata_json']??'');return ['id'=>(int)($row['id']??0),'session_id'=>(int)($row['session_id']??0),'pageview_id'=>isset($row['pageview_id'])?(int)$row['pageview_id']:null,'campaign_id'=>isset($row['campaign_id'])?(int)$row['campaign_id']:null,'landing_page_id'=>isset($row['landing_page_id'])?(int)$row['landing_page_id']:null,'short_link_id'=>isset($row['short_link_id'])?(int)$row['short_link_id']:null,'crm_lead_id'=>isset($row['crm_lead_id'])?(int)$row['crm_lead_id']:null,'event_type'=>(string)($row['event_type']??''),'event_name'=>(string)($row['event_name']??''),'element_id_preview'=>$this->preview((string)($row['element_id']??''),60),'element_text_preview'=>$this->preview((string)($row['element_text']??''),80),'element_url_present'=>$elementUrl!=='','element_url_preview'=>$this->sanitizeUrlPreview($elementUrl),'value_numeric'=>isset($row['value_numeric'])?(float)$row['value_numeric']:null,'value_text_present'=>$valueText!=='','value_text_preview'=>$this->preview($valueText,80),'score_points'=>isset($row['score_points'])?(float)$row['score_points']:null,'metadata_json_present'=>$metadata!=='','metadata_json_exposed'=>false,'occurred_at'=>$row['occurred_at']??null,'mode'=>'read-only','db_write'=>false];}
private function preview(string $value,int $max): string{return mb_substr(trim($value),0,$max);}private function sanitizeUrlPreview(string $url): string{if($url===''){return '';} $parts=parse_url($url); if(!is_array($parts)){return substr($url,0,80);} $scheme=isset($parts['scheme'])?$parts['scheme'].'://':'';$host=$parts['host']??'';$path=$parts['path']??''; return substr($scheme.$host.$path,0,140);}}
