<?php
declare(strict_types=1);
namespace App\Core\Reports;
use PDO;
final class EcosistemaMarketingFunnelReportRepository{public function __construct(private readonly PDO $pdo){}
public function listCampaigns(int $tenantId): array{$stmt=$this->pdo->prepare('SELECT id,name,code,status FROM crm_marketing_campaigns WHERE tenant_id=:tenant_id ORDER BY updated_at DESC,id DESC LIMIT 500');$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->execute();return (array)$stmt->fetchAll(PDO::FETCH_ASSOC);} 
public function listLandings(int $tenantId): array{$stmt=$this->pdo->prepare('SELECT id,name,slug,status FROM landing_pages WHERE tenant_id=:tenant_id ORDER BY updated_at DESC,id DESC LIMIT 500');$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->execute();return (array)$stmt->fetchAll(PDO::FETCH_ASSOC);} 
public function funnelCounts(int $tenantId,string $fromDate,string $toDate,?int $campaignId,?int $landingId): array{return ['clicks'=>$this->countClicks($tenantId,$fromDate,$toDate,$campaignId),'visits'=>$this->countVisits($tenantId,$fromDate,$toDate,$campaignId,$landingId),'submissions'=>$this->countSubmissions($tenantId,$fromDate,$toDate,$campaignId,$landingId),'leads'=>$this->countLeads($tenantId,$fromDate,$toDate,$campaignId),'conversions'=>$this->countConversions($tenantId,$fromDate,$toDate,$campaignId)];}
private function countClicks(int $tenantId,string $fromDate,string $toDate,?int $campaignId): int{$sql='SELECT COUNT(*) FROM url_clicks WHERE tenant_id=:tenant_id AND DATE(clicked_at) BETWEEN :from_date AND :to_date';if($campaignId!==null){$sql.=' AND campaign_id=:campaign_id';}$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':from_date',$fromDate,PDO::PARAM_STR);$stmt->bindValue(':to_date',$toDate,PDO::PARAM_STR);if($campaignId!==null){$stmt->bindValue(':campaign_id',$campaignId,PDO::PARAM_INT);} $stmt->execute();return (int)$stmt->fetchColumn();}
private function countVisits(int $tenantId,string $fromDate,string $toDate,?int $campaignId,?int $landingId): int{$sql='SELECT COUNT(*) FROM landing_visits WHERE tenant_id=:tenant_id AND DATE(visited_at) BETWEEN :from_date AND :to_date';if($campaignId!==null){$sql.=' AND campaign_id=:campaign_id';}if($landingId!==null){$sql.=' AND page_id=:landing_id';}$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':from_date',$fromDate,PDO::PARAM_STR);$stmt->bindValue(':to_date',$toDate,PDO::PARAM_STR);if($campaignId!==null){$stmt->bindValue(':campaign_id',$campaignId,PDO::PARAM_INT);}if($landingId!==null){$stmt->bindValue(':landing_id',$landingId,PDO::PARAM_INT);} $stmt->execute();return (int)$stmt->fetchColumn();}
private function countSubmissions(int $tenantId,string $fromDate,string $toDate,?int $campaignId,?int $landingId): int{$sql='SELECT COUNT(*) FROM landing_form_submissions WHERE tenant_id=:tenant_id AND DATE(submitted_at) BETWEEN :from_date AND :to_date';if($campaignId!==null){$sql.=' AND campaign_id=:campaign_id';}if($landingId!==null){$sql.=' AND page_id=:landing_id';}$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':from_date',$fromDate,PDO::PARAM_STR);$stmt->bindValue(':to_date',$toDate,PDO::PARAM_STR);if($campaignId!==null){$stmt->bindValue(':campaign_id',$campaignId,PDO::PARAM_INT);}if($landingId!==null){$stmt->bindValue(':landing_id',$landingId,PDO::PARAM_INT);} $stmt->execute();return (int)$stmt->fetchColumn();}
private function countLeads(int $tenantId,string $fromDate,string $toDate,?int $campaignId): int{$sql='SELECT COUNT(*) FROM crm_leads WHERE tenant_id=:tenant_id AND DATE(created_at) BETWEEN :from_date AND :to_date';if($campaignId!==null){$sql.=' AND campaign_id=:campaign_id';}$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':from_date',$fromDate,PDO::PARAM_STR);$stmt->bindValue(':to_date',$toDate,PDO::PARAM_STR);if($campaignId!==null){$stmt->bindValue(':campaign_id',$campaignId,PDO::PARAM_INT);} $stmt->execute();return (int)$stmt->fetchColumn();}
private function countConversions(int $tenantId,string $fromDate,string $toDate,?int $campaignId): int{$sql='SELECT COUNT(*) FROM crm_lead_conversions WHERE tenant_id=:tenant_id AND DATE(converted_at) BETWEEN :from_date AND :to_date';if($campaignId!==null){$sql.=' AND campaign_id=:campaign_id';}$stmt=$this->pdo->prepare($sql);$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':from_date',$fromDate,PDO::PARAM_STR);$stmt->bindValue(':to_date',$toDate,PDO::PARAM_STR);if($campaignId!==null){$stmt->bindValue(':campaign_id',$campaignId,PDO::PARAM_INT);} $stmt->execute();return (int)$stmt->fetchColumn();}}
