<?php $role=$contentData['role']??null; $tenants=$contentData['tenants']??[]; $errorMessage=$contentData['errorMessage']??null; if(!$role){return;} $isSystem=((int)$role['is_system'])===1; ?>
<section class="eco-card"><h1>Editar rol</h1><?php if($errorMessage): ?><div class="eco-alert"><?= e($errorMessage) ?></div><?php endif; ?><?php if($isSystem): ?><div class="eco-alert">Rol de sistema: sólo se permite editar nombre y descripción.</div><?php endif; ?>
<form method="post" action="/roles/<?= e((string)$role['id']) ?>"><input type="hidden" name="_csrf" value="<?= e((string)$csrfToken) ?>">
<label>Tenant</label><select class="eco-form-control" name="tenant_id" <?= $isSystem?'disabled':'' ?>><option value="">Global / sin tenant</option><?php foreach($tenants as $tenant): ?><option value="<?= e((string)$tenant['id']) ?>" <?= ((int)$role['tenant_id']===(int)$tenant['id'])?'selected':'' ?>><?= e($tenant['name'].' ('.$tenant['slug'].')') ?></option><?php endforeach; ?></select>
<label>Code</label><input class="eco-form-control" name="code" value="<?= e((string)$role['code']) ?>" <?= $isSystem?'readonly':'' ?> required>
<label>Name</label><input class="eco-form-control" name="name" value="<?= e((string)$role['name']) ?>" required>
<label>Description</label><textarea class="eco-form-control" name="description"><?= e((string)($role['description']??'')) ?></textarea>
<label>Scope</label><select class="eco-form-control" name="scope" <?= $isSystem?'disabled':'' ?>><option value="global" <?= $role['scope']==='global'?'selected':'' ?>>global</option><option value="tenant" <?= $role['scope']==='tenant'?'selected':'' ?>>tenant</option><option value="module" <?= $role['scope']==='module'?'selected':'' ?>>module</option></select>
<label>is_system</label><select class="eco-form-control" name="is_system" <?= $isSystem?'disabled':'' ?>><option value="0" <?= ((int)$role['is_system'])===0?'selected':'' ?>>0</option><option value="1" <?= ((int)$role['is_system'])===1?'selected':'' ?>>1</option></select>
<button class="eco-button btn" type="submit">Actualizar</button></form></section>
