<?php $detail = (array) ($contentData['detail'] ?? []); $run = (array) ($detail['run'] ?? []); $logs = (array) ($detail['logs'] ?? []); $links = (array) ($detail['module_links'] ?? []); ?>
<section class="space-y-4"><h1>Workflow Run #<?= e((string) ($run['id'] ?? 0)) ?></h1><p><a href="/workflow/runs">← Volver a ejecuciones</a></p><p><strong>Modo:</strong> read-only.</p>
<ul><li>Rule: <?= e((string) ($run['rule_name'] ?? 'N/A')) ?></li><li>Status: <?= e((string) ($run['status'] ?? '')) ?></li><li>Triggered by: <?= e((string) ($run['triggered_by_label'] ?? 'N/A')) ?></li><li>Error preview: <?= e((string) ($run['error_message_preview'] ?? '')) ?></li></ul>
<h2>Logs</h2><table><thead><tr><th>ID</th><th>Level</th><th>Action type</th><th>Message</th><th>Context JSON</th><th>Created</th></tr></thead><tbody>
<?php if ($logs === []): ?><tr><td colspan="6">Sin logs.</td></tr><?php else: foreach ($logs as $log): ?><tr><td><?= e((string) ($log['id'] ?? 0)) ?></td><td><?= e((string) ($log['level'] ?? '')) ?></td><td><?= e((string) ($log['action_type'] ?? '')) ?></td><td><?= e((string) ($log['message_preview'] ?? '')) ?></td><td><?= (($log['context_json_present'] ?? false) ? 'Sí' : 'No') ?></td><td><?= e((string) ($log['created_at'] ?? '')) ?></td></tr><?php endforeach; endif; ?>
</tbody></table>
<h2>Module links</h2><table><thead><tr><th>ID</th><th>Module</th><th>Entity table</th><th>Entity ID</th><th>Relation</th><th>Metadata JSON</th><th>Created</th></tr></thead><tbody>
<?php if ($links === []): ?><tr><td colspan="7">Sin links.</td></tr><?php else: foreach ($links as $link): ?><tr><td><?= e((string) ($link['id'] ?? 0)) ?></td><td><?= e((string) ($link['module_code'] ?? '')) ?></td><td><?= e((string) ($link['entity_table_preview'] ?? '')) ?></td><td><?= (($link['entity_id_present'] ?? false) ? 'Sí' : 'No') ?></td><td><?= e((string) ($link['relation_type'] ?? '')) ?></td><td><?= (($link['metadata_json_present'] ?? false) ? 'Sí' : 'No') ?></td><td><?= e((string) ($link['created_at'] ?? '')) ?></td></tr><?php endforeach; endif; ?>
</tbody></table></section>
