#!/usr/bin/env php
<?php
declare(strict_types=1);
use App\Core\Database\PdoFactory;
$root = dirname(__DIR__); require_once $root . '/vendor/autoload.php'; $app = require $root . '/bootstrap/app.php';
$options = getopt('', ['tenant:', 'user:', 'message:']);
$tenantId=(int)($options['tenant']??0); $userId=(int)($options['user']??0); $messageId=(int)($options['message']??0);
if($tenantId<=0||$userId<=0||$messageId<=0){fwrite(STDERR,"Uso: php scripts/mail-attachment-debug.php --tenant=1 --user=1 --message=16\n");exit(1);}
$pdo=PdoFactory::make((array)($app['config']['database']??[]));
$sql='SELECT ea.id,ea.original_filename,ea.mime_type,ea.size_bytes,ea.import_status,ea.cloud_file_id,ea.error_message,ea.raw_payload_json FROM mail_external_attachments ea INNER JOIN mail_messages m ON m.id=ea.message_id AND m.tenant_id=ea.tenant_id WHERE ea.tenant_id=:t AND m.user_id=:u AND ea.message_id=:m ORDER BY ea.id ASC';
$st=$pdo->prepare($sql); $st->execute([':t'=>$tenantId,':u'=>$userId,':m'=>$messageId]); $rows=$st->fetchAll(PDO::FETCH_ASSOC)?:[];
$sanitize=static function(string $v):string{$v=preg_replace('/\s+/',' ',trim($v))??''; return mb_substr($v,0,180);};
$out=[]; foreach($rows as $r){$raw=json_decode((string)($r['raw_payload_json']??''),true); if(!is_array($raw)){$raw=[];} $has=['imap_folder'=>!empty($raw['imap_folder']),'imap_uid'=>!empty($raw['imap_uid']),'imap_part_number'=>!empty($raw['imap_part_number'])]; $missing=[]; foreach($has as $k=>$v){ if(!$v){$missing[]=$k;} } $cloudFileId=(int)($r['cloud_file_id']??0); $linked=false; if($cloudFileId>0){$lk=$pdo->prepare('SELECT id FROM mail_attachments WHERE tenant_id=:t AND message_id=:m AND cloud_file_id=:c LIMIT 1'); $lk->execute([':t'=>$tenantId,':m'=>$messageId,':c'=>$cloudFileId]); $linked=((int)($lk->fetchColumn()?:0))>0;} $orphan=false; $orphanId=0; $probe=$pdo->prepare('SELECT id FROM cloud_files WHERE tenant_id=:t AND user_id=:u AND origin_module="mail" AND origin_table="mail_external_attachments" AND origin_id=:oid ORDER BY id DESC LIMIT 1'); $probe->execute([':t'=>$tenantId,':u'=>$userId,':oid'=>(int)$r['id']]); $orphanId=(int)($probe->fetchColumn()?:0); $orphan=$cloudFileId<=0&&$orphanId>0; $can=$missing===[]; $imported=$cloudFileId>0||((string)$r['import_status']==='imported'); $action=$imported?'already_imported':($orphan?'repair_cloud_links':($can?'import_attachment':'backfill_imap_metadata')); $lastError=(string)($r['error_message']??''); $out[]=['external_attachment_id'=>(int)$r['id'],'original_filename'=>(string)$r['original_filename'],'mime_type'=>(string)$r['mime_type'],'size_bytes'=>(int)$r['size_bytes'],'import_status'=>(string)$r['import_status'],'has_cloud_file'=>$cloudFileId>0,'cloud_file_id'=>$cloudFileId>0?$cloudFileId:null,'linked_mail_attachment'=>$linked,'possible_orphan_cloud_file'=>$orphan,'last_error'=>$sanitize($lastError),'raw_payload_has'=>$has,'missing_fields'=>$missing,'can_import_binary'=>$can,'suggested_action'=>$action];}
echo json_encode(['ok'=>true,'message_id'=>$messageId,'attachments'=>$out], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE).PHP_EOL;
