<?php
declare(strict_types=1);
namespace App\Core\Audit;
final readonly class EcosistemaUnifiedAuditService{public function __construct(private EcosistemaUnifiedAuditRepository $repository) {}
public function listEvents(int $tenantId,array $query): array{$filters=['module_code'=>trim((string)($query['module_code']??'')),'action'=>trim((string)($query['action']??'')),'from'=>$this->safeDate($query['from']??null),'to'=>$this->safeDate($query['to']??null)]; return ['events'=>array_map(fn(array $row): array=>$this->safeEvent($row),$this->repository->listEvents($tenantId,$filters,100)),'filters'=>$filters];}
public function findDetail(int $tenantId,int $auditId): ?array{if($auditId<=0){return null;} $event=$this->repository->findEventById($tenantId,$auditId); if($event===null){return null;} return ['event'=>$this->safeEvent($event),'changes'=>array_map(fn(array $r): array=>$this->safeChange($r),$this->repository->listEntityChangesForAudit($tenantId,$auditId)),'links'=>array_map(fn(array $r): array=>$this->safeLink($r),$this->repository->listLinksForAudit($tenantId,$auditId))];}
private function safeEvent(array $row): array{return ['id'=>(int)($row['id']??0),'module_code'=>(string)($row['module_code']??''),'action'=>(string)($row['action']??''),'entity_table'=>(string)($row['entity_table']??''),'entity_id'=>isset($row['entity_id'])?(int)$row['entity_id']:null,'reason_preview'=>$this->preview((string)($row['reason']??'')),'ip_preview'=>$this->maskIp((string)($row['ip_address']??'')),'user_agent_preview'=>$this->preview((string)($row['user_agent']??''),60),'change_count'=>(int)($row['change_count']??0),'link_count'=>(int)($row['link_count']??0),'created_at'=>(string)($row['created_at']??'')];}
private function safeChange(array $row): array{return ['id'=>(int)($row['id']??0),'module_code'=>(string)($row['module_code']??''),'entity_table'=>(string)($row['entity_table']??''),'entity_id'=>isset($row['entity_id'])?(int)$row['entity_id']:null,'change_type'=>(string)($row['change_type']??''),'changed_by_user_id'=>isset($row['changed_by_user_id'])?(int)$row['changed_by_user_id']:null,'changed_at'=>(string)($row['changed_at']??''),'before_json_present'=>trim((string)($row['before_json']??''))!=='','after_json_present'=>trim((string)($row['after_json']??''))!==''];}
private function safeLink(array $row): array{return ['id'=>(int)($row['id']??0),'module_code'=>(string)($row['module_code']??''),'entity_table'=>(string)($row['entity_table']??''),'entity_id'=>isset($row['entity_id'])?(int)$row['entity_id']:null,'relation_type'=>(string)($row['relation_type']??''),'metadata_json_present'=>trim((string)($row['metadata_json']??''))!=='','created_at'=>(string)($row['created_at']??'')];}
private function preview(string $value,int $limit=40): string{$v=trim($value); return $v===''?'':(mb_strlen($v)>$limit?mb_substr($v,0,$limit).'…':$v);} private function maskIp(string $ip): string{$ip=trim($ip); if($ip===''){return '';} return filter_var($ip,FILTER_VALIDATE_IP,FILTER_FLAG_IPV4)?(string)preg_replace('/\.\d+$/','.xxx',$ip):(mb_substr($ip,0,6).'…');} private function safeDate(mixed $value): string{$v=trim((string)$value); return preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)===1?$v:'';}}
