<?php
declare(strict_types=1);
namespace App\Core\Audit;
use PDO;
final readonly class EcosistemaUnifiedAuditRepository{public function __construct(private PDO $pdo) {}
public function listEvents(int $tenantId,array $filters=[],int $limit=100): array{$sql='SELECT a.id,a.tenant_id,a.user_id,a.session_id,a.module_code,a.action,a.entity_table,a.entity_id,a.reason,a.ip_address,a.user_agent,a.created_at,COUNT(DISTINCT c.id) AS change_count,COUNT(DISTINCT l.id) AS link_count FROM core_audit a LEFT JOIN audit_entity_changes c ON c.audit_id=a.id AND c.tenant_id=a.tenant_id LEFT JOIN module_audit_links l ON l.audit_id=a.id AND l.tenant_id=a.tenant_id WHERE a.tenant_id=:tenant_id';$params=[':tenant_id'=>$tenantId]; if(($filters['module_code']??'')!==''){ $sql.=' AND a.module_code=:module_code'; $params[':module_code']=(string)$filters['module_code']; } if(($filters['action']??'')!==''){ $sql.=' AND a.action=:action'; $params[':action']=(string)$filters['action']; } if(($filters['from']??'')!==''){ $sql.=' AND a.created_at>=:created_from'; $params[':created_from']=(string)$filters['from'].' 00:00:00'; } if(($filters['to']??'')!==''){ $sql.=' AND a.created_at<=:created_to'; $params[':created_to']=(string)$filters['to'].' 23:59:59'; } $sql.=' GROUP BY a.id,a.tenant_id,a.user_id,a.session_id,a.module_code,a.action,a.entity_table,a.entity_id,a.reason,a.ip_address,a.user_agent,a.created_at ORDER BY a.created_at DESC,a.id DESC LIMIT :limit'; $stmt=$this->pdo->prepare($sql); foreach($params as $k=>$v){$stmt->bindValue($k,$v);} $stmt->bindValue(':limit',max(1,min($limit,200)),PDO::PARAM_INT); $stmt->execute(); return $stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}
public function findEventById(int $tenantId,int $auditId): ?array{$stmt=$this->pdo->prepare('SELECT id,tenant_id,user_id,session_id,module_code,action,entity_table,entity_id,reason,ip_address,user_agent,created_at FROM core_audit WHERE tenant_id=:tenant_id AND id=:id LIMIT 1');$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':id',$auditId,PDO::PARAM_INT);$stmt->execute();$row=$stmt->fetch(PDO::FETCH_ASSOC);return is_array($row)?$row:null;}
public function listEntityChangesForAudit(int $tenantId,int $auditId): array{$stmt=$this->pdo->prepare('SELECT id,module_code,entity_table,entity_id,change_type,changed_by_user_id,changed_at,before_json,after_json FROM audit_entity_changes WHERE tenant_id=:tenant_id AND audit_id=:audit_id ORDER BY changed_at DESC,id DESC LIMIT 50');$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':audit_id',$auditId,PDO::PARAM_INT);$stmt->execute();return $stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}
public function listLinksForAudit(int $tenantId,int $auditId): array{$stmt=$this->pdo->prepare('SELECT id,module_code,entity_table,entity_id,relation_type,metadata_json,created_at FROM module_audit_links WHERE tenant_id=:tenant_id AND audit_id=:audit_id ORDER BY created_at DESC,id DESC LIMIT 50');$stmt->bindValue(':tenant_id',$tenantId,PDO::PARAM_INT);$stmt->bindValue(':audit_id',$auditId,PDO::PARAM_INT);$stmt->execute();return $stmt->fetchAll(PDO::FETCH_ASSOC)?:[];}}
